package com.sinc.mobile.data.repository

import androidx.arch.core.executor.testing.InstantTaskExecutorRule
import com.google.common.truth.Truth.assertThat
import com.google.gson.Gson
import com.sinc.mobile.data.di.DatabaseModule
import com.sinc.mobile.data.di.NetworkModule
import com.sinc.mobile.data.local.SincMobileDatabase
import com.sinc.mobile.data.local.dao.MovimientoPendienteDao
import com.sinc.mobile.data.local.entities.MovimientoPendienteEntity
import com.sinc.mobile.data.network.api.MovimientoApiService
import com.sinc.mobile.data.session.SessionManager
import com.sinc.mobile.domain.model.MovimientoPendiente
import dagger.hilt.android.testing.HiltAndroidRule
import dagger.hilt.android.testing.HiltAndroidTest
import dagger.hilt.android.testing.UninstallModules
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import okhttp3.OkHttpClient
import okhttp3.ResponseBody
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.junit.After
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.time.LocalDateTime
import javax.inject.Inject

@UninstallModules(DatabaseModule::class, NetworkModule::class)
@HiltAndroidTest
@ExperimentalCoroutinesApi
class MovimientoRepositoryImplTest {

    @get:Rule(order = 0)
    var hiltRule = HiltAndroidRule(this)

    @get:Rule(order = 1)
    var instantTaskExecutorRule = InstantTaskExecutorRule()

    private lateinit var mockWebServer: MockWebServer
    private lateinit var movimientoApiService: MovimientoApiService
    private lateinit var movimientoRepository: MovimientoRepositoryImpl

    @Inject
    lateinit var db: SincMobileDatabase

    @Inject
    lateinit var movimientoPendienteDao: MovimientoPendienteDao

    @Inject
    lateinit var sessionManager: SessionManager

    private val gson = Gson()

    @Before
    fun setup() {
        hiltRule.inject()

        mockWebServer = MockWebServer()
        mockWebServer.start()

        val okHttpClient = OkHttpClient.Builder().build()

        movimientoApiService = Retrofit.Builder()
            .baseUrl(mockWebServer.url("/"))
            .client(okHttpClient)
            .addConverterFactory(GsonConverterFactory.create(gson))
            .build()
            .create(MovimientoApiService::class.java)

        movimientoRepository = MovimientoRepositoryImpl(
            movimientoPendienteDao,
            movimientoApiService,
            sessionManager
        )
    }

    @After
    fun teardown() {
        mockWebServer.shutdown()
        db.close()
    }

    private fun createTestMovimientoPendiente(id: Long, sincronizado: Boolean = false): MovimientoPendiente {
        val now = LocalDateTime.now()
        return MovimientoPendiente(
            id = id,
            unidadProductivaId = 1,
            especieId = 1,
            categoriaId = 1,
            razaId = 1,
            cantidad = 10,
            motivoMovimientoId = 1,
            destinoTraslado = "Destino",
            observaciones = "Observaciones de prueba",
            fechaRegistro = now,
            sincronizado = sincronizado
        )
    }

    private fun createTestMovimientoPendienteEntity(id: Long, sincronizado: Boolean = false): MovimientoPendienteEntity {
        val now = LocalDateTime.now()
        return MovimientoPendienteEntity(
            id = id,
            unidad_productiva_id = 1,
            especie_id = 1,
            categoria_id = 1,
            raza_id = 1,
            cantidad = 10,
            motivo_movimiento_id = 1,
            destino_traslado = "Destino",
            observaciones = "Observaciones de prueba",
            fecha_registro = now,
            sincronizado = sincronizado,
            fecha_creacion_local = now
        )
    }

    @Test
    fun saveMovimientoLocal_success_insertsIntoDb() = runBlocking {
        val movimiento = createTestMovimientoPendiente(id = 0) // ID will be autogenerated
        val result = movimientoRepository.saveMovimientoLocal(movimiento)

        assertThat(result.isSuccess).isTrue()
        val savedMovimientos = movimientoPendienteDao.getAllMovimientosPendientes().first()
        assertThat(savedMovimientos).hasSize(1)
        assertThat(savedMovimientos[0].unidad_productiva_id).isEqualTo(movimiento.unidadProductivaId)
    }

    @Test
    fun getMovimientosPendientes_returnsCorrectData() = runBlocking {
        val entity1 = createTestMovimientoPendienteEntity(id = 1, sincronizado = false)
        val entity2 = createTestMovimientoPendienteEntity(id = 2, sincronizado = true)
        movimientoPendienteDao.insertAll(listOf(entity1, entity2))

        val movimientos = movimientoRepository.getMovimientosPendientes().first()
        assertThat(movimientos).hasSize(2)
        assertThat(movimientos[0].id).isEqualTo(entity1.id)
        assertThat(movimientos[1].id).isEqualTo(entity2.id)
    }

    @Test
    fun syncMovimientosPendientes_success_sendsToApiAndMarksAsSynced() = runBlocking {
        // Given
        val authToken = "test_token"
        sessionManager.saveAuthToken(authToken)

        val unsyncedMovimiento = createTestMovimientoPendienteEntity(id = 1, sincronizado = false)
        movimientoPendienteDao.insert(unsyncedMovimiento)

        mockWebServer.enqueue(MockResponse().setResponseCode(200).setBody("{ \"message\": \"Movimientos guardados exitosamente.\" }"))

        // When
        val result = movimientoRepository.syncMovimientosPendientes()
        val request = mockWebServer.takeRequest()

        // Then
        assertThat(result.isSuccess).isTrue()
        assertThat(request.path).isEqualTo("/movil/cuaderno/movimientos")
        assertThat(request.method).isEqualTo("POST")

        val updatedMovimiento = movimientoPendienteDao.getAllMovimientosPendientes().first().first()
        assertThat(updatedMovimiento.sincronizado).isTrue()
    }

    @Test
    fun syncMovimientosPendientes_apiError_doesNotMarkAsSynced() = runBlocking {
        // Given
        val authToken = "test_token"
        sessionManager.saveAuthToken(authToken)

        val unsyncedMovimiento = createTestMovimientoPendienteEntity(id = 1, sincronizado = false)
        movimientoPendienteDao.insert(unsyncedMovimiento)

        mockWebServer.enqueue(MockResponse().setResponseCode(500).setBody("{ \"error\": \"Server Error\" }"))

        // When
        val result = movimientoRepository.syncMovimientosPendientes()
        mockWebServer.takeRequest()

        // Then
        assertThat(result.isFailure).isTrue()
        val updatedMovimiento = movimientoPendienteDao.getAllMovimientosPendientes().first().first()
        assertThat(updatedMovimiento.sincronizado).isFalse()
    }

    @Test
    fun syncMovimientosPendientes_noUnsyncedMovements_returnsSuccess() = runBlocking {
        // Given: No unsynced movements in DB
        val authToken = "test_token"
        sessionManager.saveAuthToken(authToken)

        // When
        val result = movimientoRepository.syncMovimientosPendientes()

        // Then
        assertThat(result.isSuccess).isTrue()
        // Verify no API call was made
        assertThat(mockWebServer.requestCount).isEqualTo(0)
    }

    @Test
    fun syncMovimientosPendientes_noAuthToken_returnsFailure() = runBlocking {
        // Given
        sessionManager.clearAuthToken()

        val unsyncedMovimiento = createTestMovimientoPendienteEntity(id = 1, sincronizado = false)
        movimientoPendienteDao.insert(unsyncedMovimiento)

        // When
        val result = movimientoRepository.syncMovimientosPendientes()

        // Then
        assertThat(result.isFailure).isTrue()
        val exception = result.exceptionOrNull()
        assertThat(exception).isNotNull()
        assertThat(exception).hasMessageThat().contains("No hay token de autenticación disponible")
        // Verify no API call was made
        assertThat(mockWebServer.requestCount).isEqualTo(0)
    }
}
